version: "3.8"
services:
 app:
  container_name: app
  image: node
  restart: always
  build:
    dockerfile: Dockerfile
  volumes:
    - './src:/app/src'
  ports:
  - "3000:3000"
  environment:
    - CHOKIDAR_USEPOLLING=true
  links:
  - mongo
 mongo:
  container_name: mongo
  image: mongo
  volumes:
  - ./data:/data/db
  ports:
  - '27017:27017'